name = "panduan-qada-solat"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[pages_build_config]
build_command = "npx @cloudflare/next-on-pages@1"
destination = ".vercel/output/static"
